version: 2
jobs:
    build:
        docker:
            # Use the same Docker base as the project
            - image: python:3.7.3-stretch

        steps:
            - checkout
             - setup_remote_docker:
                version: 19.03.13
                docker_layer_caching: true
            # Download and cache dependencies
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "requirements.txt" }}
                    # fallback to using the latest cache if no exact match is found
                    - v1-dependencies-
            # - run:
            #     name: Install Docker client
            #     command: |
            #         set -x
            #         VER="17.03.0-ce"
            #         curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            #         tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            #         mv /tmp/docker/* /usr/bin
            - run:
                name: install dependencies
                command: |
                    python3 -m venv venv
                    . venv/bin/activate
                    make install
                    # Install hadolint
                    wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
                    chmod +x /bin/hadolint
            
            - save_cache:
                paths:
                    - ./venv
                key: v1-dependencies-{{ checksum "requirements.txt" }}

            # run lint!
            - run:
                name: run lint
                command: |
                    set -x
                    ls -la
                    . venv/bin/activate
                    make lint
        # TODO: Do I need a workflow?